### ISSUE TITLE
Using YouTube thumbnails instead of Vimeo

### ISSUE THREAD

**Issue by codepuncher** [ItinerisLtd/lite-vimeo-embed#2]
https://github.com/ItinerisLtd/lite-vimeo-embed/blob/c6c58ebd8b67150c7c80c60b225d05ec956d5be5/src/lite-vm-embed.js#L34

**Comment by dulgermuhammet** [comment]
> https://github.com/ItinerisLtd/lite-vimeo-embed/blob/c6c58ebd8b67150c7c80c60b225d05ec956d5be5/src/lite-vm-embed.js#L34

I think vimeo has not public image cdn for getting thumbnails like youtube, we need to use 3rd party service to get thumbnails if its ok. e.g. https://vumbnail.com/

**Comment by codepuncher** [comment]
Yep that's fine
